#!/bin/bash

# 检查参数数量是否正确
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 folder_name"
    exit 1
fi

# 获取参数中的文件夹名称
folder_name=$1

# 设置默认的模板文件夹名称
default_template_folder="_Template"
template_folder=${2:-$default_template_folder}

# 检查 Template 文件夹是否存在
if [ ! -d "$template_folder" ]; then
    echo "Error: Template folder not found"
    exit 1
fi

# 创建新的文件夹
mkdir "$folder_name"

# 复制 Template 文件夹下的所有文件到新创建的文件夹中
cp -r $template_folder/* "$folder_name"

echo "Folder '$folder_name' created with files from Template folder"
